# Generated by Django 5.1.2 on 2024-10-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfocus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
