# Generated by Django 5.1.2 on 2024-10-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfocus', '0003_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
