# Generated by Django 5.1.2 on 2024-10-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genfocus', '0004_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cpf',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
